### PR TITLE
setup react in ui folder

### PR DESCRIPTION
**Pull request by stefan-kenyon**
Setup React for the front end.
If you want to test just download, navigate to ui folder in commandline/POWERshell, then run
"npm init"
wait for installation, then
"npm run start"

Then localhost:8080 I believe.

### CODE REVIEW

**Comment by MorganW09** [comment]
Looking great! Got that green background!

Just to confirm I ran "npm install" not "npm init" to get the project working.

**Comment by MorganW09** [comment]
Also, would you be able to add a line in the .gitignore for the node modules folder? After that I'll merge it in.

**Comment by stefan-kenyon** [comment]
Oh yeah, that thing.

I just did that to confirm css was working.

And I put a line down at the end of the current gitignore file for node
modules.

**Comment by stefan-kenyon** [comment]
Nevermind, git was tracking it. Now it is in there.

**Comment by MorganW09** [comment]
Looks good, I've merged this in now. I'm going to create a dev branch today, and in the future lets target PRs to hit that branch instead of the master branch.

Thanks for getting the UI working! Looking forward to seeing where this goes.

**Comment by stefan-kenyon** [comment]
So dev instead of me naming specific branches like 'setting up react'?

Also, what exactly are you wanting to get started first?

Are you trying to make a little question/answer quiz?

**Comment by MorganW09** [comment]
So this PR was merged into the master branch, which is the only branch at the moment on this project. 

But a better branching strategy would be to have a master branch and then a dev branch. Things that are a work in progress or haven't been tested well get merged into the dev branch. Then at some point we merge dev into master and have a "release". 

That keeps the master branch cleaner and allows some separation between branches. Which on a small project isn't that important, but worth doing.

So I've created new api routes to both create and read questions. I thought that would probably be the best place to get started. I might try to get started on using github's project features to we can kind of track work.

**Pull request merged**
